# Test-Invoice.ps1
# This script simulates a Vendor's Accounting Software or an AI OCR tool 
# sending an invoice to your Power Automate Flow.

param(
    [Parameter(Mandatory=$true, HelpMessage="The HTTP POST URL generated by your Power Automate Flow")]
    [string]$WebhookUrl
)

Write-Host "Preparing to send Invoice Payload to Power Automate..." -ForegroundColor Cyan

# The JSON Payload (What the vendor's system generates)
$invoiceData = @{
    InvoiceNumber = "INV-$(Get-Random -Minimum 1000 -Maximum 9999)"
    VendorName = "Acme Corporation"
    Amount = (Get-Random -Minimum 100 -Maximum 5000) + 0.99
    DateIssued = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")
}

$jsonPayload = $invoiceData | ConvertTo-Json

Write-Host "Payload Generated:`n$jsonPayload" -ForegroundColor Yellow

# Fire the payload at the Flow's URL
try {
    $response = Invoke-RestMethod -Uri $WebhookUrl -Method Post -Body $jsonPayload -ContentType "application/json"
    
    Write-Host "`n[SUCCESS] Invoice successfully transmitted!" -ForegroundColor Green
    Write-Host "Response from Power Automate:"
    $response | Format-List
}
catch {
    Write-Host "`n[ERROR] Failed to send invoice. Ensure your Flow URL is correct and the Flow is turned on." -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
}